/**
 * Prisma AIRS Tool Result Redactor (tool_result_persist)
 *
 * SYNCHRONOUS hook — fires before tool results are written to session JSONL.
 * Applies regex-based DLP masking to redact PII/credentials from tool outputs.
 * Optionally checks scan cache for AIRS DLP signals from tool-guard hook.
 *
 * Cannot call AIRS API (async) — relies on regex patterns + cached scan results.
 */

import { getCachedScanResult } from "../../src/scan-cache";
import type { ScanResult } from "../../src/scanner";

// Content item types matching OpenClaw's AgentMessage
interface ContentItem {
  type: string;
  text?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
}

interface ToolResultMessage {
  role?: string;
  toolCallId?: string;
  toolName?: string;
  content?: ContentItem[];
  isError?: boolean;
  timestamp?: number;
}

interface ToolResultPersistEvent {
  toolName?: string;
  toolCallId?: string;
  message: ToolResultMessage;
  isSynthetic?: boolean;
}

interface HookContext {
  agentId?: string;
  sessionKey?: string;
  toolName?: string;
  toolCallId?: string;
  cfg?: {
    plugins?: {
      entries?: {
        "prisma-airs"?: {
          config?: {
            profile_name?: string;
            app_name?: string;
            tool_redact_mode?: string;
            fail_closed?: boolean;
          };
        };
      };
    };
  };
}

interface HookResult {
  message?: ToolResultMessage;
}

/**
 * Mask sensitive data in content using regex patterns.
 * Reuses the same patterns as the outbound handler.
 */
function maskSensitiveData(content: string): string {
  let masked = content;

  // Social Security Numbers (XXX-XX-XXXX)
  masked = masked.replace(/\b\d{3}-\d{2}-\d{4}\b/g, "[SSN REDACTED]");

  // Credit Card Numbers (with or without spaces/dashes)
  masked = masked.replace(/\b(?:\d{4}[-\s]?){3}\d{4}\b/g, "[CARD REDACTED]");

  // Email addresses
  masked = masked.replace(
    /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g,
    "[EMAIL REDACTED]"
  );

  // API keys and tokens (common patterns)
  masked = masked.replace(
    /\b(?:sk-|pk-|api[_-]?key[_-]?|token[_-]?|secret[_-]?|password[_-]?)[a-zA-Z0-9_-]{16,}\b/gi,
    "[API KEY REDACTED]"
  );

  // AWS keys
  masked = masked.replace(/\b(?:AKIA|ABIA|ACCA|ASIA)[A-Z0-9]{16}\b/g, "[AWS KEY REDACTED]");

  // Generic long alphanumeric strings that look like secrets (40+ chars)
  masked = masked.replace(/\b[a-zA-Z0-9_-]{40,}\b/g, (match) => {
    if (/[a-z]/.test(match) && /[A-Z]/.test(match) && /[0-9]/.test(match)) {
      return "[SECRET REDACTED]";
    }
    return match;
  });

  // US Phone numbers
  masked = masked.replace(
    /\b(?:\+1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/g,
    "[PHONE REDACTED]"
  );

  // IP addresses (private ranges)
  masked = masked.replace(
    /\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3})\b/g,
    "[IP REDACTED]"
  );

  return masked;
}

/**
 * Main hook handler — MUST be synchronous (tool_result_persist requirement)
 */
const handler = (event: ToolResultPersistEvent, ctx: HookContext): HookResult | void => {
  const cfg = ctx.cfg?.plugins?.entries?.["prisma-airs"]?.config;
  const mode = cfg?.tool_redact_mode ?? "deterministic";

  // Check if redaction is enabled
  if (mode === "off") {
    return;
  }

  // Skip synthetic results (generated by guard/repair steps)
  if (event.isSynthetic) {
    return;
  }

  // Validate message has content
  const message = event.message;
  if (!message?.content || !Array.isArray(message.content) || message.content.length === 0) {
    return;
  }

  // Check scan cache for AIRS DLP signal (from tool-guard hook)
  const sessionKey = ctx.sessionKey ?? "unknown";
  const cached: ScanResult | undefined = getCachedScanResult(sessionKey);
  const hasDlpSignal = cached?.responseDetected?.dlp === true;

  // Process each content item
  let anyChanged = false;
  const newContent: ContentItem[] = message.content.map((item: ContentItem) => {
    // Only process text content
    if (item.type !== "text" || typeof item.text !== "string") {
      return item;
    }

    const masked = maskSensitiveData(item.text);
    if (masked !== item.text) {
      anyChanged = true;
      return { ...item, text: masked };
    }

    return item;
  });

  // Only return modified message if something changed
  if (!anyChanged) {
    return;
  }

  const action = hasDlpSignal ? "cache_dlp" : "regex";

  console.log(
    JSON.stringify({
      event: "prisma_airs_tool_redact",
      timestamp: new Date().toISOString(),
      sessionKey,
      toolName: event.toolName ?? message.toolName ?? "unknown",
      action,
      cachedDlp: hasDlpSignal,
    })
  );

  return {
    message: {
      ...message,
      content: newContent,
    },
  };
};

export default handler;
